export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS';
export const REFRESH_RECOMMENDATIONS = 'REFRESH_RECOMMENDATIONS';
export const GET_RECOMMENDER_INFO = 'GET_RECOMMENDER_INFO';
export const IMPORT_NEWSGROUPS = 'IMPORT_NEWSGROUPS';
